#!/bin/bash


# Lien
# Dead simple file upload program
# - Upload to different file hosts
# - Shorten links
# - Log your uploads
# - Clear you logs

red="\e[31m"
grn="\e[32m"
ylw="\e[33m"
cyn="\e[36m"
blu="\e[34m"
prp="\e[35m"
bprp="\e[35;1m"
rst="\e[0m"

####### Configuration ########

# path to save screenshots and logs
save_dir="$HOME/pics/scrots"

# application to open when lien is called
# with the -e tag
editor_app="gimp"

##############################

method=0
hosts=0
delay=0
edit=0

copy() {
	echo $1 | xclip -i -selection clipboard
}

screenshot() {
	case $1 in
		1)
			scrot -u -d $2 $fname
			;;
		2)
			scrot -s -d $2 $fname
			;;
		3)
			scrot -d $2 $fname
			;;
	esac
}

upload() {
	local id=$( curl -sf -F "file=@${1}" https://0x0.st )
	if [[ -z "${id// }" ]]
	then
		echo -e "${red}Error $rst"
		notify-send "Failed to upload ${1}"
		exit 1
	else
		echo "${id}"
		local file_path=$( readlink -f $save_dir/$1 )
		echo "${file_path} - ${id}" >> $save_dir/lien_logs
		notify-send "Uploaded" "${1}"
		copy $id
	fi
}

shorten() {
	local id=$( curl -sF"shorten=${1}" https://0x0.st )
	echo ${id}
	echo "${1} - ${id}" >> $save_dir/lien_logs
	copy $id
}

clear_logs() {
	if [ ! -f $save_dir/lien_logs ]
	then
		echo -e "${red}No logs${rst}"
	else
		rm -f $save_dir/lien_logs
		echo "Logs cleared."
	fi
}

print_logs() {
	if [ ! -f $save_dir/lien_logs ]
	then
		echo -e "${red}No logs${rst}"
	else
		tac $save_dir/lien_logs
	fi
}

while getopts :hlusafd:o options
do
	case $options in
		u)
			method=1
			;;
		s)
			method=2
			;;
		a)
			method=3
			;;
		f)
			doUpload=1
			fhost="$OPTARG"
			;;
		d)
			delay="$OPTARG"
			;;
		l)
			print_logs
			exit 0
			;;
		o)
			shorten "${OPTARG}"
			exit 0
			;;
		c)
			clear_logs
			exit 0
			;;
		h|?)
			print_help
			exit 0
			;;
		*)
			print_help
			exit 0
			;;
	esac
done

shift $(( $OPTIND -1 ))

# Process the remaining args
if [ $# -gt 1 ]
then
	echo "Too many arguments."
	echo "Try lien -h for help."
	exit 0
elif [ $# -lt 0 ]
then
	echo "Too few arguments."
	echo "Try lien -h for help."
	exit 0
elif [ $# -eq 0 ]
then
	fname=$( date +"%T-%d.%m.%y" )
	fname="$fname.png"
else
	fname=$1
fi


main() {
	case $doUpload in
		1)
			case $method in
				0)
					upload $1
					;;
				*)
					screenshot $method $delay
					upload $fname
					rm $fname
					;;
			esac
			;;
		0)
			case $method in
				0)
					exit 0
					;;
				*)
					screenshot $method $delay
					mv $fname $save_dir/$fname
					;;
			esac
			;;
	esac
}

main

# exit if none of the others
# options end the program
exit 1
